const DAY=86400000;
const templates={none:[],stock:[['Order placed',10],['Delivery / on site',1]],bespoke:[['Design information complete',50],['Tender issued',45],['Appointment / Order',38],['Shop drawings approved',30],['Manufacture complete',5],['Delivery / on site',1]],subcontract:[['Scope complete',45],['Tender issued',40],['Tender returns',30],['Analysis complete',25],['Award',20],['Design / submittals complete',12],['Mobilisation',3]]};
let state=JSON.parse(localStorage.getItem('hxProgramme')||'null')||{tasks:[{id:1,wbs:'1.1',name:'Enabling works',start:'2026-09-21',duration:5,progress:100,status:'Complete',trade:'General',proc:'none',pred:''},{id:2,wbs:'2.1',name:'Basement excavation',start:'2026-09-28',duration:15,progress:55,status:'On Track',trade:'Groundworks',proc:'subcontract',pred:'1FS'},{id:3,wbs:'2.2',name:'RC basement structure',start:'2026-10-19',duration:20,progress:0,status:'Not Started',trade:'Concrete',proc:'subcontract',pred:'2FS'},{id:4,wbs:'5.1',name:'Bespoke joinery installation',start:'2026-11-16',duration:20,progress:0,status:'Not Started',trade:'Joinery',proc:'bespoke',pred:'3FS'}],risks:[],updates:[],baseline:null};
function save(){localStorage.setItem('hxProgramme',JSON.stringify(state))}function addDays(d,n){let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}function finish(t){return addDays(t.start,Math.max(0,t.duration-1))}function daysBetween(a,b){return Math.ceil((new Date(b)-new Date(a))/DAY)}
function procurement(t){return (templates[t.proc]||[]).map((m,i)=>({id:t.id+'-'+i,task:t.id,name:m[0],required:addDays(t.start,-m[1]),done:!!(t.procDone||{})[i]}))}
function allProc(){return state.tasks.flatMap(procurement)}function riskLevel(m){let d=daysBetween(new Date().toISOString().slice(0,10),m.required);if(m.done)return'Complete';if(d<0)return'Critical';if(d<=3)return'At Risk';if(d<=10)return'Watch';return'Upcoming'}
function autoRisks(){let manual=state.risks.filter(r=>!r.auto);allProc().forEach(m=>{let l=riskLevel(m);if(['Critical','At Risk'].includes(l)){let t=state.tasks.find(x=>x.id===m.task);manual.push({id:'P-'+m.id,auto:true,task:t.id,title:t.name,trigger:m.name+' '+(l==='Critical'?'overdue':'due shortly'),owner:'Project Team',level:l,exposure:l==='Critical'?Math.max(1,Math.abs(daysBetween(new Date().toISOString().slice(0,10),m.required))):0,status:'Open'})}});state.risks=manual;save()}
function schedule(){let changed=true,n=0;while(changed&&n++<20){changed=false;state.tasks.forEach(t=>{if(!t.pred)return;let m=t.pred.match(/(\d+)(FS|SS|FF|SF)?([+-]\d+)?/);if(!m)return;let p=state.tasks.find(x=>x.id==m[1]);if(!p)return;let type=m[2]||'FS',lag=+(m[3]||0),s=t.start;if(type==='FS')s=addDays(finish(p),1+lag);if(type==='SS')s=addDays(p.start,lag);if(type==='FF')s=addDays(finish(p),lag-(t.duration-1));if(type==='SF')s=addDays(p.start,lag-(t.duration-1));if(s!==t.start){t.start=s;changed=true}})}autoRisks();save();render()}
function addTask(){let name=prompt('Activity name');if(!name)return;let start=prompt('Start date YYYY-MM-DD',new Date().toISOString().slice(0,10));let duration=+(prompt('Duration (days)','5')||5);let proc=prompt('Procurement template: none / stock / bespoke / subcontract','subcontract')||'none';state.tasks.push({id:Date.now(),wbs:(state.tasks.length+1)+'.0',name,start,duration,progress:0,status:'Not Started',trade:'TBC',proc,pred:''});schedule()}
function updateTask(id){let t=state.tasks.find(x=>x.id===id),s=prompt('Status: Not Started / On Track / Blocked / Delayed / Complete',t.status);if(!s)return;t.status=s;t.progress=s==='Complete'?100:+prompt('% complete',t.progress)||t.progress;let note=prompt('Comment / reason','')||'';state.updates.unshift({task:id,status:s,progress:t.progress,note,at:new Date().toISOString()});if(['Blocked','Delayed'].includes(s))state.risks.push({id:'R-'+Date.now(),task:id,title:t.name,trigger:s+': '+note,owner:'Project Team',level:s==='Delayed'?'Critical':'At Risk',exposure:0,status:'Open'});save();autoRisks();render()}
function toggleProc(task,i){let t=state.tasks.find(x=>x.id===task);t.procDone=t.procDone||{};t.procDone[i]=!t.procDone[i];autoRisks();render()}
function baseline(){state.baseline=state.tasks.map(t=>({id:t.id,start:t.start,finish:finish(t)}));save();alert('Baseline B01 saved')}
function csv(){let rows=[['WBS','Activity','Start','Finish','Duration','Progress','Status','Trade'],...state.tasks.map(t=>[t.wbs,t.name,t.start,finish(t),t.duration,t.progress,t.status,t.trade])];let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}));a.download='HX-Programme.csv';a.click()}
function render(){autoRisks();let gt=document.querySelector('#gantt tbody');if(gt)gt.innerHTML=state.tasks.map(t=>`<tr><td>${t.wbs}</td><td>${t.name}<small><br>${t.pred?'Pred '+t.pred:''}</small></td><td>${t.start}</td><td>${finish(t)}</td><td>${t.duration}d</td><td>${t.progress}%</td><td>${t.status}</td></tr>`).join('');let rt=document.querySelector('#risk tbody');if(rt)rt.innerHTML=state.risks.map(r=>`<tr><td>${r.id}</td><td>${r.title}</td><td>${r.trigger}</td><td>${r.owner}</td><td><span class="pill ${r.level==='Critical'?'risk':'watch'}">${r.level}</span></td><td>${r.exposure||0}d</td></tr>`).join('');let pt=document.querySelector('#proc tbody');if(pt)pt.innerHTML=allProc().map(m=>{let t=state.tasks.find(x=>x.id===m.task),i=+m.id.split('-').pop(),l=riskLevel(m);return`<tr><td>${t.name}</td><td>${m.name}</td><td>${m.required}</td><td><button onclick="toggleProc(${t.id},${i})"><span class="pill ${m.done?'ok':l==='Critical'?'risk':l==='Watch'||l==='At Risk'?'watch':''}">${m.done?'Complete':l}</span></button></td></tr>`}).join('');let lt=document.querySelector('#look tbody');if(lt){let now=new Date(),end=new Date(now.getTime()+14*DAY);let q=state.tasks.filter(t=>new Date(t.start)<=end&&new Date(finish(t))>=new Date(now.getTime()-7*DAY));lt.innerHTML=q.map(t=>`<tr><td>${t.name}</td><td>${t.trade}</td><td>${finish(t)}</td><td>${t.status} · ${t.progress}%</td><td><button onclick="updateTask(${t.id})">Update</button></td></tr>`).join('')||'<tr><td colspan=5>No activities in current window</td></tr>'}let c=document.querySelectorAll('.card strong');if(c.length){let avg=Math.round(state.tasks.reduce((a,t)=>a+t.progress,0)/state.tasks.length);c[0].textContent=avg+'%';c[1].textContent=state.risks.length;c[2].textContent=state.risks.filter(r=>r.level==='Critical').length;c[3].textContent=allProc().filter(m=>riskLevel(m)==='Critical').length;c[4].textContent=Math.max(0,...state.risks.map(r=>r.exposure||0))+' days'}}
document.addEventListener('DOMContentLoaded',render);window.HX={state,schedule,addTask,updateTask,toggleProc,baseline,csv,render};