-- HX Programme production schema (PostgreSQL/Supabase-ready)
create table projects(id uuid primary key, name text not null, code text, start_date date, target_completion date, status text default 'Active', created_at timestamptz default now());
create table profiles(id uuid primary key, full_name text, email text, company text, created_at timestamptz default now());
create table project_members(id uuid primary key, project_id uuid references projects(id), user_id uuid references profiles(id), role text not null, active boolean default true);
create table tasks(id uuid primary key, project_id uuid references projects(id), parent_id uuid references tasks(id), wbs text, name text not null, location text, trade text, responsible_user uuid references profiles(id), start_date date, finish_date date, duration_days int, progress numeric default 0, status text default 'Not Started', critical boolean default false, total_float_days int default 0, procurement_type text, created_at timestamptz default now());
create table dependencies(id uuid primary key, project_id uuid references projects(id), predecessor_id uuid references tasks(id), successor_id uuid references tasks(id), dependency_type text default 'FS', lag_days int default 0);
create table baselines(id uuid primary key, project_id uuid references projects(id), name text not null, approved_by uuid references profiles(id), approved_at timestamptz, locked boolean default true);
create table baseline_tasks(id uuid primary key, baseline_id uuid references baselines(id), task_id uuid references tasks(id), start_date date, finish_date date, duration_days int);
create table procurement_milestones(id uuid primary key, project_id uuid references projects(id), task_id uuid references tasks(id), name text not null, required_date date, forecast_date date, completed_at timestamptz, status text default 'Upcoming', owner uuid references profiles(id));
create table progress_updates(id uuid primary key, project_id uuid references projects(id), task_id uuid references tasks(id), user_id uuid references profiles(id), status text, progress numeric, revised_finish date, reason text, note text, created_at timestamptz default now());
create table risks(id uuid primary key, project_id uuid references projects(id), task_id uuid references tasks(id), procurement_milestone_id uuid references procurement_milestones(id), title text not null, category text, owner uuid references profiles(id), probability text, impact_days int default 0, float_days int default 0, completion_impact_days int default 0, level text default 'Watch', status text default 'Open', mitigation text, action_due date, auto_generated boolean default false, created_at timestamptz default now(), closed_at timestamptz);
create table risk_actions(id uuid primary key, risk_id uuid references risks(id), owner uuid references profiles(id), action text not null, due_date date, completed_at timestamptz);
create table evidence(id uuid primary key, project_id uuid references projects(id), task_id uuid references tasks(id), risk_id uuid references risks(id), uploaded_by uuid references profiles(id), file_url text, caption text, created_at timestamptz default now());
create table notifications(id uuid primary key, project_id uuid references projects(id), user_id uuid references profiles(id), event_type text, title text, body text, urgency text default 'Normal', read_at timestamptz, created_at timestamptz default now());
create table audit_events(id uuid primary key, project_id uuid references projects(id), user_id uuid references profiles(id), entity_type text, entity_id uuid, action text, before_data jsonb, after_data jsonb, created_at timestamptz default now());
create index tasks_project_idx on tasks(project_id); create index procurement_task_idx on procurement_milestones(task_id); create index risks_project_idx on risks(project_id); create index notifications_user_idx on notifications(user_id);